set(AUDIO_EFFECT_LIBS 
    AudioPlayer
    Delay
    Distortion
    Filter
    Flanger
    NoiseGate
    Oscillator
    PingPongDelay
    Reverb
    SimpleDistortion
    SimpleEQ
    ThreeBandEqualizer
	Chorus
)