#include "AudioPlayer/PluginProcessor.h"
#include "Delay/PluginProcessor.h"
#include "Distortion/PluginProcessor.h"
#include "Filter/PluginProcessor.h"
#include "Flanger/PluginProcessor.h"
#include "NoiseGate/PluginProcessor.h"
#include "Oscillator/PluginProcessor.h"
#include "PingPongDelay/PluginProcessor.h"
#include "Reverb/PluginProcessor.h"
#include "ThreeBandEqualizer/PluginProcessor.h"
#include "Chorus/PluginProcessor.h"
#include "JCM800/PluginProcessor.h"
#include "Tuner/PluginProcessor.h"
#include "TS808/PluginProcessor.h"

#include "DS2/PluginProcessor.h"